title : When dosa meets Litti - a North-South love story!
name : Soma Chaudhary and Sree Ganesh
description : The wedding website of Soma and Sree! 
theme: jekyll-theme-slate
syntax_highlighting: true
colored: colored # Leave blank for black and white icons
# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
